//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenguaVivaCliente.ServicioLenguaViva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLenguaViva.IGestionUsuarios")]
    public interface IGestionUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/IniciarSesion", ReplyAction="http://tempuri.org/IGestionUsuarios/IniciarSesionResponse")]
        ServicioContrato.SesionUsuario IniciarSesion(string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/IniciarSesion", ReplyAction="http://tempuri.org/IGestionUsuarios/IniciarSesionResponse")]
        System.Threading.Tasks.Task<ServicioContrato.SesionUsuario> IniciarSesionAsync(string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/RegistrarAdministrador", ReplyAction="http://tempuri.org/IGestionUsuarios/RegistrarAdministradorResponse")]
        bool RegistrarAdministrador(ServicioContrato.AdministradorDTO administradorDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/RegistrarAdministrador", ReplyAction="http://tempuri.org/IGestionUsuarios/RegistrarAdministradorResponse")]
        System.Threading.Tasks.Task<bool> RegistrarAdministradorAsync(ServicioContrato.AdministradorDTO administradorDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/CargarIdiomas", ReplyAction="http://tempuri.org/IGestionUsuarios/CargarIdiomasResponse")]
        ServicioContrato.IdiomaDTO[] CargarIdiomas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/CargarIdiomas", ReplyAction="http://tempuri.org/IGestionUsuarios/CargarIdiomasResponse")]
        System.Threading.Tasks.Task<ServicioContrato.IdiomaDTO[]> CargarIdiomasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/RegistrarProfesor", ReplyAction="http://tempuri.org/IGestionUsuarios/RegistrarProfesorResponse")]
        bool RegistrarProfesor(ServicioContrato.ProfesorDTO profesorDTO, int[] idIdiomas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/RegistrarProfesor", ReplyAction="http://tempuri.org/IGestionUsuarios/RegistrarProfesorResponse")]
        System.Threading.Tasks.Task<bool> RegistrarProfesorAsync(ServicioContrato.ProfesorDTO profesorDTO, int[] idIdiomas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/RegistrarAlumno", ReplyAction="http://tempuri.org/IGestionUsuarios/RegistrarAlumnoResponse")]
        bool RegistrarAlumno(ServicioContrato.AlumnoDTO alumnoDTO, ServicioContrato.IdiomaNivelDTO[] idiomasNivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/RegistrarAlumno", ReplyAction="http://tempuri.org/IGestionUsuarios/RegistrarAlumnoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarAlumnoAsync(ServicioContrato.AlumnoDTO alumnoDTO, ServicioContrato.IdiomaNivelDTO[] idiomasNivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/BuscarUsuarios", ReplyAction="http://tempuri.org/IGestionUsuarios/BuscarUsuariosResponse")]
        ServicioContrato.UsuarioDTO[] BuscarUsuarios(string criterioBusqueda, int tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/BuscarUsuarios", ReplyAction="http://tempuri.org/IGestionUsuarios/BuscarUsuariosResponse")]
        System.Threading.Tasks.Task<ServicioContrato.UsuarioDTO[]> BuscarUsuariosAsync(string criterioBusqueda, int tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/EliminarUsuario", ReplyAction="http://tempuri.org/IGestionUsuarios/EliminarUsuarioResponse")]
        ServicioContrato.UsuarioDTO EliminarUsuario(string correo, int tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/EliminarUsuario", ReplyAction="http://tempuri.org/IGestionUsuarios/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<ServicioContrato.UsuarioDTO> EliminarUsuarioAsync(string correo, int tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/ModificarAdministrador", ReplyAction="http://tempuri.org/IGestionUsuarios/ModificarAdministradorResponse")]
        bool ModificarAdministrador(ServicioContrato.AdministradorDTO administradorDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/ModificarAdministrador", ReplyAction="http://tempuri.org/IGestionUsuarios/ModificarAdministradorResponse")]
        System.Threading.Tasks.Task<bool> ModificarAdministradorAsync(ServicioContrato.AdministradorDTO administradorDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/ObtenerAdministradorPorCorreo", ReplyAction="http://tempuri.org/IGestionUsuarios/ObtenerAdministradorPorCorreoResponse")]
        ServicioContrato.AdministradorDTO ObtenerAdministradorPorCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/ObtenerAdministradorPorCorreo", ReplyAction="http://tempuri.org/IGestionUsuarios/ObtenerAdministradorPorCorreoResponse")]
        System.Threading.Tasks.Task<ServicioContrato.AdministradorDTO> ObtenerAdministradorPorCorreoAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/ObtenerProfesorPorCorreo", ReplyAction="http://tempuri.org/IGestionUsuarios/ObtenerProfesorPorCorreoResponse")]
        ServicioContrato.ProfesorDTO ObtenerProfesorPorCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/ObtenerProfesorPorCorreo", ReplyAction="http://tempuri.org/IGestionUsuarios/ObtenerProfesorPorCorreoResponse")]
        System.Threading.Tasks.Task<ServicioContrato.ProfesorDTO> ObtenerProfesorPorCorreoAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/ObtenerAlumnoPorCorreo", ReplyAction="http://tempuri.org/IGestionUsuarios/ObtenerAlumnoPorCorreoResponse")]
        ServicioContrato.AlumnoDTO ObtenerAlumnoPorCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/ObtenerAlumnoPorCorreo", ReplyAction="http://tempuri.org/IGestionUsuarios/ObtenerAlumnoPorCorreoResponse")]
        System.Threading.Tasks.Task<ServicioContrato.AlumnoDTO> ObtenerAlumnoPorCorreoAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionUsuariosChannel : LenguaVivaCliente.ServicioLenguaViva.IGestionUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionUsuariosClient : System.ServiceModel.ClientBase<LenguaVivaCliente.ServicioLenguaViva.IGestionUsuarios>, LenguaVivaCliente.ServicioLenguaViva.IGestionUsuarios {
        
        public GestionUsuariosClient() {
        }
        
        public GestionUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicioContrato.SesionUsuario IniciarSesion(string usuario, string contrasenia) {
            return base.Channel.IniciarSesion(usuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.SesionUsuario> IniciarSesionAsync(string usuario, string contrasenia) {
            return base.Channel.IniciarSesionAsync(usuario, contrasenia);
        }
        
        public bool RegistrarAdministrador(ServicioContrato.AdministradorDTO administradorDTO) {
            return base.Channel.RegistrarAdministrador(administradorDTO);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarAdministradorAsync(ServicioContrato.AdministradorDTO administradorDTO) {
            return base.Channel.RegistrarAdministradorAsync(administradorDTO);
        }
        
        public ServicioContrato.IdiomaDTO[] CargarIdiomas() {
            return base.Channel.CargarIdiomas();
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.IdiomaDTO[]> CargarIdiomasAsync() {
            return base.Channel.CargarIdiomasAsync();
        }
        
        public bool RegistrarProfesor(ServicioContrato.ProfesorDTO profesorDTO, int[] idIdiomas) {
            return base.Channel.RegistrarProfesor(profesorDTO, idIdiomas);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarProfesorAsync(ServicioContrato.ProfesorDTO profesorDTO, int[] idIdiomas) {
            return base.Channel.RegistrarProfesorAsync(profesorDTO, idIdiomas);
        }
        
        public bool RegistrarAlumno(ServicioContrato.AlumnoDTO alumnoDTO, ServicioContrato.IdiomaNivelDTO[] idiomasNivel) {
            return base.Channel.RegistrarAlumno(alumnoDTO, idiomasNivel);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarAlumnoAsync(ServicioContrato.AlumnoDTO alumnoDTO, ServicioContrato.IdiomaNivelDTO[] idiomasNivel) {
            return base.Channel.RegistrarAlumnoAsync(alumnoDTO, idiomasNivel);
        }
        
        public ServicioContrato.UsuarioDTO[] BuscarUsuarios(string criterioBusqueda, int tipoUsuario) {
            return base.Channel.BuscarUsuarios(criterioBusqueda, tipoUsuario);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.UsuarioDTO[]> BuscarUsuariosAsync(string criterioBusqueda, int tipoUsuario) {
            return base.Channel.BuscarUsuariosAsync(criterioBusqueda, tipoUsuario);
        }
        
        public ServicioContrato.UsuarioDTO EliminarUsuario(string correo, int tipoUsuario) {
            return base.Channel.EliminarUsuario(correo, tipoUsuario);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.UsuarioDTO> EliminarUsuarioAsync(string correo, int tipoUsuario) {
            return base.Channel.EliminarUsuarioAsync(correo, tipoUsuario);
        }
        
        public bool ModificarAdministrador(ServicioContrato.AdministradorDTO administradorDTO) {
            return base.Channel.ModificarAdministrador(administradorDTO);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarAdministradorAsync(ServicioContrato.AdministradorDTO administradorDTO) {
            return base.Channel.ModificarAdministradorAsync(administradorDTO);
        }
        
        public ServicioContrato.AdministradorDTO ObtenerAdministradorPorCorreo(string correo) {
            return base.Channel.ObtenerAdministradorPorCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.AdministradorDTO> ObtenerAdministradorPorCorreoAsync(string correo) {
            return base.Channel.ObtenerAdministradorPorCorreoAsync(correo);
        }
        
        public ServicioContrato.ProfesorDTO ObtenerProfesorPorCorreo(string correo) {
            return base.Channel.ObtenerProfesorPorCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.ProfesorDTO> ObtenerProfesorPorCorreoAsync(string correo) {
            return base.Channel.ObtenerProfesorPorCorreoAsync(correo);
        }
        
        public ServicioContrato.AlumnoDTO ObtenerAlumnoPorCorreo(string correo) {
            return base.Channel.ObtenerAlumnoPorCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.AlumnoDTO> ObtenerAlumnoPorCorreoAsync(string correo) {
            return base.Channel.ObtenerAlumnoPorCorreoAsync(correo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLenguaViva.IGestionAlumnos")]
    public interface IGestionAlumnos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlumnos/RegistrarPago", ReplyAction="http://tempuri.org/IGestionAlumnos/RegistrarPagoResponse")]
        bool RegistrarPago(int cantidadPagada, int idInscripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlumnos/RegistrarPago", ReplyAction="http://tempuri.org/IGestionAlumnos/RegistrarPagoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarPagoAsync(int cantidadPagada, int idInscripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlumnos/ObtenerReciboPago", ReplyAction="http://tempuri.org/IGestionAlumnos/ObtenerReciboPagoResponse")]
        ServicioContrato.ReciboPago ObtenerReciboPago(int idInscripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlumnos/ObtenerReciboPago", ReplyAction="http://tempuri.org/IGestionAlumnos/ObtenerReciboPagoResponse")]
        System.Threading.Tasks.Task<ServicioContrato.ReciboPago> ObtenerReciboPagoAsync(int idInscripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlumnos/EnviarCorreoReciboPago", ReplyAction="http://tempuri.org/IGestionAlumnos/EnviarCorreoReciboPagoResponse")]
        bool EnviarCorreoReciboPago(int idInscripcion, string pdfPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlumnos/EnviarCorreoReciboPago", ReplyAction="http://tempuri.org/IGestionAlumnos/EnviarCorreoReciboPagoResponse")]
        System.Threading.Tasks.Task<bool> EnviarCorreoReciboPagoAsync(int idInscripcion, string pdfPath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionAlumnosChannel : LenguaVivaCliente.ServicioLenguaViva.IGestionAlumnos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionAlumnosClient : System.ServiceModel.ClientBase<LenguaVivaCliente.ServicioLenguaViva.IGestionAlumnos>, LenguaVivaCliente.ServicioLenguaViva.IGestionAlumnos {
        
        public GestionAlumnosClient() {
        }
        
        public GestionAlumnosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionAlumnosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionAlumnosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionAlumnosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarPago(int cantidadPagada, int idInscripcion) {
            return base.Channel.RegistrarPago(cantidadPagada, idInscripcion);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarPagoAsync(int cantidadPagada, int idInscripcion) {
            return base.Channel.RegistrarPagoAsync(cantidadPagada, idInscripcion);
        }
        
        public ServicioContrato.ReciboPago ObtenerReciboPago(int idInscripcion) {
            return base.Channel.ObtenerReciboPago(idInscripcion);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.ReciboPago> ObtenerReciboPagoAsync(int idInscripcion) {
            return base.Channel.ObtenerReciboPagoAsync(idInscripcion);
        }
        
        public bool EnviarCorreoReciboPago(int idInscripcion, string pdfPath) {
            return base.Channel.EnviarCorreoReciboPago(idInscripcion, pdfPath);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarCorreoReciboPagoAsync(int idInscripcion, string pdfPath) {
            return base.Channel.EnviarCorreoReciboPagoAsync(idInscripcion, pdfPath);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLenguaViva.IGestionCursos")]
    public interface IGestionCursos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombre", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreResponse")]
        ServicioContrato.CursoDTO[] ObtenerCursosPorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombre", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreResponse")]
        System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreIdioma", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreIdiomaResponse")]
        ServicioContrato.CursoDTO[] ObtenerCursosPorNombreIdioma(string nombreIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreIdioma", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreIdiomaResponse")]
        System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreIdiomaAsync(string nombreIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNivel", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNivelResponse")]
        ServicioContrato.CursoDTO[] ObtenerCursosPorNivel(int nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNivel", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNivelResponse")]
        System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNivelAsync(int nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreProfesor", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreProfesorResponse")]
        ServicioContrato.CursoDTO[] ObtenerCursosPorNombreProfesor(string nombreProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreProfesor", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreProfesorResponse")]
        System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreProfesorAsync(string nombreProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/RegistrarCurso", ReplyAction="http://tempuri.org/IGestionCursos/RegistrarCursoResponse")]
        bool RegistrarCurso(ServicioContrato.CursoDTO cursoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/RegistrarCurso", ReplyAction="http://tempuri.org/IGestionCursos/RegistrarCursoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarCursoAsync(ServicioContrato.CursoDTO cursoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerProfesoresPorNombre", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerProfesoresPorNombreResponse")]
        ServicioContrato.ProfesorDTO[] ObtenerProfesoresPorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerProfesoresPorNombre", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerProfesoresPorNombreResponse")]
        System.Threading.Tasks.Task<ServicioContrato.ProfesorDTO[]> ObtenerProfesoresPorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerProfesorPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerProfesorPorIDResponse")]
        ServicioContrato.ProfesorDTO ObtenerProfesorPorID(int idProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerProfesorPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerProfesorPorIDResponse")]
        System.Threading.Tasks.Task<ServicioContrato.ProfesorDTO> ObtenerProfesorPorIDAsync(int idProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerIdiomas", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerIdiomasResponse")]
        ServicioContrato.IdiomaDTO[] ObtenerIdiomas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerIdiomas", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerIdiomasResponse")]
        System.Threading.Tasks.Task<ServicioContrato.IdiomaDTO[]> ObtenerIdiomasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerIdiomaPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerIdiomaPorIDResponse")]
        ServicioContrato.IdiomaDTO ObtenerIdiomaPorID(int idIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerIdiomaPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerIdiomaPorIDResponse")]
        System.Threading.Tasks.Task<ServicioContrato.IdiomaDTO> ObtenerIdiomaPorIDAsync(int idIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursoPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursoPorIDResponse")]
        ServicioContrato.CursoDTO ObtenerCursoPorID(int idCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursoPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursoPorIDResponse")]
        System.Threading.Tasks.Task<ServicioContrato.CursoDTO> ObtenerCursoPorIDAsync(int idCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ModificarCurso", ReplyAction="http://tempuri.org/IGestionCursos/ModificarCursoResponse")]
        bool ModificarCurso(ServicioContrato.CursoDTO cursoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ModificarCurso", ReplyAction="http://tempuri.org/IGestionCursos/ModificarCursoResponse")]
        System.Threading.Tasks.Task<bool> ModificarCursoAsync(ServicioContrato.CursoDTO cursoDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionCursosChannel : LenguaVivaCliente.ServicioLenguaViva.IGestionCursos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionCursosClient : System.ServiceModel.ClientBase<LenguaVivaCliente.ServicioLenguaViva.IGestionCursos>, LenguaVivaCliente.ServicioLenguaViva.IGestionCursos {
        
        public GestionCursosClient() {
        }
        
        public GestionCursosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionCursosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCursosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCursosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicioContrato.CursoDTO[] ObtenerCursosPorNombre(string nombre) {
            return base.Channel.ObtenerCursosPorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreAsync(string nombre) {
            return base.Channel.ObtenerCursosPorNombreAsync(nombre);
        }
        
        public ServicioContrato.CursoDTO[] ObtenerCursosPorNombreIdioma(string nombreIdioma) {
            return base.Channel.ObtenerCursosPorNombreIdioma(nombreIdioma);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreIdiomaAsync(string nombreIdioma) {
            return base.Channel.ObtenerCursosPorNombreIdiomaAsync(nombreIdioma);
        }
        
        public ServicioContrato.CursoDTO[] ObtenerCursosPorNivel(int nivel) {
            return base.Channel.ObtenerCursosPorNivel(nivel);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNivelAsync(int nivel) {
            return base.Channel.ObtenerCursosPorNivelAsync(nivel);
        }
        
        public ServicioContrato.CursoDTO[] ObtenerCursosPorNombreProfesor(string nombreProfesor) {
            return base.Channel.ObtenerCursosPorNombreProfesor(nombreProfesor);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreProfesorAsync(string nombreProfesor) {
            return base.Channel.ObtenerCursosPorNombreProfesorAsync(nombreProfesor);
        }
        
        public bool RegistrarCurso(ServicioContrato.CursoDTO cursoDTO) {
            return base.Channel.RegistrarCurso(cursoDTO);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarCursoAsync(ServicioContrato.CursoDTO cursoDTO) {
            return base.Channel.RegistrarCursoAsync(cursoDTO);
        }
        
        public ServicioContrato.ProfesorDTO[] ObtenerProfesoresPorNombre(string nombre) {
            return base.Channel.ObtenerProfesoresPorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.ProfesorDTO[]> ObtenerProfesoresPorNombreAsync(string nombre) {
            return base.Channel.ObtenerProfesoresPorNombreAsync(nombre);
        }
        
        public ServicioContrato.ProfesorDTO ObtenerProfesorPorID(int idProfesor) {
            return base.Channel.ObtenerProfesorPorID(idProfesor);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.ProfesorDTO> ObtenerProfesorPorIDAsync(int idProfesor) {
            return base.Channel.ObtenerProfesorPorIDAsync(idProfesor);
        }
        
        public ServicioContrato.IdiomaDTO[] ObtenerIdiomas() {
            return base.Channel.ObtenerIdiomas();
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.IdiomaDTO[]> ObtenerIdiomasAsync() {
            return base.Channel.ObtenerIdiomasAsync();
        }
        
        public ServicioContrato.IdiomaDTO ObtenerIdiomaPorID(int idIdioma) {
            return base.Channel.ObtenerIdiomaPorID(idIdioma);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.IdiomaDTO> ObtenerIdiomaPorIDAsync(int idIdioma) {
            return base.Channel.ObtenerIdiomaPorIDAsync(idIdioma);
        }
        
        public ServicioContrato.CursoDTO ObtenerCursoPorID(int idCurso) {
            return base.Channel.ObtenerCursoPorID(idCurso);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.CursoDTO> ObtenerCursoPorIDAsync(int idCurso) {
            return base.Channel.ObtenerCursoPorIDAsync(idCurso);
        }
        
        public bool ModificarCurso(ServicioContrato.CursoDTO cursoDTO) {
            return base.Channel.ModificarCurso(cursoDTO);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarCursoAsync(ServicioContrato.CursoDTO cursoDTO) {
            return base.Channel.ModificarCursoAsync(cursoDTO);
        }
    }
}
