//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenguaVivaCliente.ServicioLenguaViva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLenguaViva.IGestionUsuarios")]
    public interface IGestionUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/IniciarSesion", ReplyAction="http://tempuri.org/IGestionUsuarios/IniciarSesionResponse")]
        bool IniciarSesion(string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/IniciarSesion", ReplyAction="http://tempuri.org/IGestionUsuarios/IniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(string usuario, string contrasenia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionUsuariosChannel : LenguaVivaCliente.ServicioLenguaViva.IGestionUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionUsuariosClient : System.ServiceModel.ClientBase<LenguaVivaCliente.ServicioLenguaViva.IGestionUsuarios>, LenguaVivaCliente.ServicioLenguaViva.IGestionUsuarios {
        
        public GestionUsuariosClient() {
        }
        
        public GestionUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IniciarSesion(string usuario, string contrasenia) {
            return base.Channel.IniciarSesion(usuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(string usuario, string contrasenia) {
            return base.Channel.IniciarSesionAsync(usuario, contrasenia);
        }
    }
}
