//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenguaVivaCliente.ServicioLenguaViva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLenguaViva.IGestionUsuarios")]
    public interface IGestionUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/IniciarSesion", ReplyAction="http://tempuri.org/IGestionUsuarios/IniciarSesionResponse")]
        bool IniciarSesion(string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/IniciarSesion", ReplyAction="http://tempuri.org/IGestionUsuarios/IniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/RegistrarAdministrador", ReplyAction="http://tempuri.org/IGestionUsuarios/RegistrarAdministradorResponse")]
        bool RegistrarAdministrador(ServicioContrato.AdministradorDTO administradorDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuarios/RegistrarAdministrador", ReplyAction="http://tempuri.org/IGestionUsuarios/RegistrarAdministradorResponse")]
        System.Threading.Tasks.Task<bool> RegistrarAdministradorAsync(ServicioContrato.AdministradorDTO administradorDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionUsuariosChannel : LenguaVivaCliente.ServicioLenguaViva.IGestionUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionUsuariosClient : System.ServiceModel.ClientBase<LenguaVivaCliente.ServicioLenguaViva.IGestionUsuarios>, LenguaVivaCliente.ServicioLenguaViva.IGestionUsuarios {
        
        public GestionUsuariosClient() {
        }
        
        public GestionUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IniciarSesion(string usuario, string contrasenia) {
            return base.Channel.IniciarSesion(usuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(string usuario, string contrasenia) {
            return base.Channel.IniciarSesionAsync(usuario, contrasenia);
        }
        
        public bool RegistrarAdministrador(ServicioContrato.AdministradorDTO administradorDTO) {
            return base.Channel.RegistrarAdministrador(administradorDTO);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarAdministradorAsync(ServicioContrato.AdministradorDTO administradorDTO) {
            return base.Channel.RegistrarAdministradorAsync(administradorDTO);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLenguaViva.IGestionCursos")]
    public interface IGestionCursos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombre", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreResponse")]
        ServicioContrato.CursoDTO[] ObtenerCursosPorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombre", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreResponse")]
        System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreIdioma", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreIdiomaResponse")]
        ServicioContrato.CursoDTO[] ObtenerCursosPorNombreIdioma(string nombreIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreIdioma", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreIdiomaResponse")]
        System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreIdiomaAsync(string nombreIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNivel", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNivelResponse")]
        ServicioContrato.CursoDTO[] ObtenerCursosPorNivel(int nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNivel", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNivelResponse")]
        System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNivelAsync(int nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreProfesor", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreProfesorResponse")]
        ServicioContrato.CursoDTO[] ObtenerCursosPorNombreProfesor(string nombreProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreProfesor", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursosPorNombreProfesorResponse")]
        System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreProfesorAsync(string nombreProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/RegistrarCurso", ReplyAction="http://tempuri.org/IGestionCursos/RegistrarCursoResponse")]
        bool RegistrarCurso(ServicioContrato.CursoDTO cursoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/RegistrarCurso", ReplyAction="http://tempuri.org/IGestionCursos/RegistrarCursoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarCursoAsync(ServicioContrato.CursoDTO cursoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerProfesoresPorNombre", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerProfesoresPorNombreResponse")]
        ServicioContrato.ProfesorDTO[] ObtenerProfesoresPorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerProfesoresPorNombre", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerProfesoresPorNombreResponse")]
        System.Threading.Tasks.Task<ServicioContrato.ProfesorDTO[]> ObtenerProfesoresPorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerProfesorPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerProfesorPorIDResponse")]
        ServicioContrato.ProfesorDTO ObtenerProfesorPorID(int idProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerProfesorPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerProfesorPorIDResponse")]
        System.Threading.Tasks.Task<ServicioContrato.ProfesorDTO> ObtenerProfesorPorIDAsync(int idProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerIdiomas", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerIdiomasResponse")]
        ServicioContrato.IdiomaDTO[] ObtenerIdiomas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerIdiomas", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerIdiomasResponse")]
        System.Threading.Tasks.Task<ServicioContrato.IdiomaDTO[]> ObtenerIdiomasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerIdiomaPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerIdiomaPorIDResponse")]
        ServicioContrato.IdiomaDTO ObtenerIdiomaPorID(int idIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerIdiomaPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerIdiomaPorIDResponse")]
        System.Threading.Tasks.Task<ServicioContrato.IdiomaDTO> ObtenerIdiomaPorIDAsync(int idIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursoPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursoPorIDResponse")]
        ServicioContrato.CursoDTO ObtenerCursoPorID(int idCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ObtenerCursoPorID", ReplyAction="http://tempuri.org/IGestionCursos/ObtenerCursoPorIDResponse")]
        System.Threading.Tasks.Task<ServicioContrato.CursoDTO> ObtenerCursoPorIDAsync(int idCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ModificarCurso", ReplyAction="http://tempuri.org/IGestionCursos/ModificarCursoResponse")]
        bool ModificarCurso(ServicioContrato.CursoDTO cursoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCursos/ModificarCurso", ReplyAction="http://tempuri.org/IGestionCursos/ModificarCursoResponse")]
        System.Threading.Tasks.Task<bool> ModificarCursoAsync(ServicioContrato.CursoDTO cursoDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionCursosChannel : LenguaVivaCliente.ServicioLenguaViva.IGestionCursos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionCursosClient : System.ServiceModel.ClientBase<LenguaVivaCliente.ServicioLenguaViva.IGestionCursos>, LenguaVivaCliente.ServicioLenguaViva.IGestionCursos {
        
        public GestionCursosClient() {
        }
        
        public GestionCursosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionCursosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCursosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCursosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicioContrato.CursoDTO[] ObtenerCursosPorNombre(string nombre) {
            return base.Channel.ObtenerCursosPorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreAsync(string nombre) {
            return base.Channel.ObtenerCursosPorNombreAsync(nombre);
        }
        
        public ServicioContrato.CursoDTO[] ObtenerCursosPorNombreIdioma(string nombreIdioma) {
            return base.Channel.ObtenerCursosPorNombreIdioma(nombreIdioma);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreIdiomaAsync(string nombreIdioma) {
            return base.Channel.ObtenerCursosPorNombreIdiomaAsync(nombreIdioma);
        }
        
        public ServicioContrato.CursoDTO[] ObtenerCursosPorNivel(int nivel) {
            return base.Channel.ObtenerCursosPorNivel(nivel);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNivelAsync(int nivel) {
            return base.Channel.ObtenerCursosPorNivelAsync(nivel);
        }
        
        public ServicioContrato.CursoDTO[] ObtenerCursosPorNombreProfesor(string nombreProfesor) {
            return base.Channel.ObtenerCursosPorNombreProfesor(nombreProfesor);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.CursoDTO[]> ObtenerCursosPorNombreProfesorAsync(string nombreProfesor) {
            return base.Channel.ObtenerCursosPorNombreProfesorAsync(nombreProfesor);
        }
        
        public bool RegistrarCurso(ServicioContrato.CursoDTO cursoDTO) {
            return base.Channel.RegistrarCurso(cursoDTO);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarCursoAsync(ServicioContrato.CursoDTO cursoDTO) {
            return base.Channel.RegistrarCursoAsync(cursoDTO);
        }
        
        public ServicioContrato.ProfesorDTO[] ObtenerProfesoresPorNombre(string nombre) {
            return base.Channel.ObtenerProfesoresPorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.ProfesorDTO[]> ObtenerProfesoresPorNombreAsync(string nombre) {
            return base.Channel.ObtenerProfesoresPorNombreAsync(nombre);
        }
        
        public ServicioContrato.ProfesorDTO ObtenerProfesorPorID(int idProfesor) {
            return base.Channel.ObtenerProfesorPorID(idProfesor);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.ProfesorDTO> ObtenerProfesorPorIDAsync(int idProfesor) {
            return base.Channel.ObtenerProfesorPorIDAsync(idProfesor);
        }
        
        public ServicioContrato.IdiomaDTO[] ObtenerIdiomas() {
            return base.Channel.ObtenerIdiomas();
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.IdiomaDTO[]> ObtenerIdiomasAsync() {
            return base.Channel.ObtenerIdiomasAsync();
        }
        
        public ServicioContrato.IdiomaDTO ObtenerIdiomaPorID(int idIdioma) {
            return base.Channel.ObtenerIdiomaPorID(idIdioma);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.IdiomaDTO> ObtenerIdiomaPorIDAsync(int idIdioma) {
            return base.Channel.ObtenerIdiomaPorIDAsync(idIdioma);
        }
        
        public ServicioContrato.CursoDTO ObtenerCursoPorID(int idCurso) {
            return base.Channel.ObtenerCursoPorID(idCurso);
        }
        
        public System.Threading.Tasks.Task<ServicioContrato.CursoDTO> ObtenerCursoPorIDAsync(int idCurso) {
            return base.Channel.ObtenerCursoPorIDAsync(idCurso);
        }
        
        public bool ModificarCurso(ServicioContrato.CursoDTO cursoDTO) {
            return base.Channel.ModificarCurso(cursoDTO);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarCursoAsync(ServicioContrato.CursoDTO cursoDTO) {
            return base.Channel.ModificarCursoAsync(cursoDTO);
        }
    }
}
